[package]
name = "example-wasmtime-host-tokio"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
aioduct = { workspace = true, features = ["tokio", "rustls", "rustls-ring", "wasmtime"] }
http.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wasmtime = { workspace = true, features = ["cranelift"] }
wasmtime-wasi = { workspace = true, features = ["p2"] }
wasmtime-wasi-http = { workspace = true, features = ["p2"] }
