[package]
name = "aioduct-wasm-demo"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
aioduct = { workspace = true, features = ["wasm", "json"] }
base64 = { workspace = true }
http = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = ["Headers", "Response"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
